plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: /Users/david/Source/Samus/appauth-angular-app/.yarn/releases/yarn-berry.js
